table dim_cliente
	lineageTag: c766fcf2-2311-4d11-b696-1739fd46b248

	measure 'cliente en riesgo' =
			IF(
			    [variaci贸n utilidad %] < 0 && [variaci贸n ordenes %] < 0,1,0)
		formatString: 0
		lineageTag: aad00570-31ae-4fe5-9cbf-2ed255e613e2

	measure 'total clientes en riesgo' = CALCULATE( DISTINCTCOUNT( dim_cliente[CustomerCategoryID]), FILTER(ALL(dim_cliente),dim_cliente[cliente en riesgo] = 1))
		formatString: 0
		lineageTag: efa71464-5d31-4bb0-87ef-0021bfb357f0

	measure '% Clientes en Riesgo' =
			
			DIVIDE(
			    [Total Clientes en Riesgo],
			    DISTINCTCOUNT(dim_cliente[CustomerID])
			)
		lineageTag: 65756104-2b7f-4730-9437-34299065f803

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nivel de Riesgo Avanzado' = ```
			
			SWITCH(
			    TRUE(),
			    [Variaci贸n Utilidad %] < -0.2 
			        && [variaci贸n ordenes %] < -0.2, " Alto Riesgo",
			    [Variaci贸n Utilidad %] < 0, " Riesgo Moderado",
			    " Estable"
			)
			```
		lineageTag: 85e3afb4-f01c-4c5e-9bf1-2ecc08e30bde

	measure 'Total Clientes' = DISTINCTCOUNT(dim_cliente[CustomerID])
		formatString: 0
		lineageTag: 5a108d29-dcf2-4791-bbed-9a005c4cf2a8

	column CustomerID
		dataType: string
		lineageTag: f08c9aa2-ec45-4af3-a7c7-1fd3691bb3c8
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 1bb42ead-7c12-4dd5-a3de-4bf8ecbf9f7b
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column CustomerCategoryID
		dataType: string
		lineageTag: 899b21d4-ef27-49ca-bbec-6b5cfd410713
		summarizeBy: none
		sourceColumn: CustomerCategoryID

		annotation SummarizationSetBy = Automatic

	column CustomerCategoryName
		dataType: string
		lineageTag: 3e514a47-afca-4449-91e3-5f2edbbf362d
		summarizeBy: none
		sourceColumn: CustomerCategoryName

		annotation SummarizationSetBy = Automatic

	column BuyingGroupID
		dataType: string
		lineageTag: 2450c88c-b662-4e04-8c4a-0b5fb39c5e4e
		summarizeBy: none
		sourceColumn: BuyingGroupID

		annotation SummarizationSetBy = Automatic

	column BuyingGroupName
		dataType: string
		lineageTag: 949a61bd-9562-4deb-9a04-f83905a13da8
		summarizeBy: none
		sourceColumn: BuyingGroupName

		annotation SummarizationSetBy = Automatic

	column CreditLimit
		dataType: double
		lineageTag: 14385f72-3cf9-4b29-8083-38af7a09a014
		summarizeBy: sum
		sourceColumn: CreditLimit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PaymentDays
		dataType: int64
		formatString: 0
		lineageTag: a0d7f668-741c-4a5e-8e53-88919733a6c5
		summarizeBy: sum
		sourceColumn: PaymentDays

		annotation SummarizationSetBy = Automatic

	column IsOnCreditHold
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e9e237a9-1e92-4fb6-9a64-9bf40fbce59b
		summarizeBy: none
		sourceColumn: IsOnCreditHold

		annotation SummarizationSetBy = Automatic

	column AccountOpenedDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 95e9d5f1-1595-4292-bcce-b7ce40f90fb5
		summarizeBy: none
		sourceColumn: AccountOpenedDate

		variation Variaci贸n
			isDefault
			relationship: 64a28f4a-37de-4fca-9c8b-7995b809957c
			defaultHierarchy: LocalDateTable_ad73385f-5c16-457e-b422-9e4bbe9b04e0.'Jerarqu铆a de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryCityID
		dataType: string
		lineageTag: 9dc5e45c-2908-43e5-836d-96ecd4496729
		summarizeBy: none
		sourceColumn: DeliveryCityID

		annotation SummarizationSetBy = Automatic

	column PostalCityID
		dataType: string
		lineageTag: 59a2266d-18fe-4b19-a460-b064616f4546
		summarizeBy: none
		sourceColumn: PostalCityID

		annotation SummarizationSetBy = Automatic

	column IsStatementSent
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 12adb101-9944-4349-95b0-530386c2653e
		summarizeBy: none
		sourceColumn: IsStatementSent

		annotation SummarizationSetBy = Automatic

	partition dim_cliente = m
		mode: import
		source =
				let
				    Origen = Sql.Databases(".\SQLEXPRESS"),
				    WideWorldImporters = Origen{[Name="WideWorldImporters"]}[Data],
				    dbo_sp_dim_customer_powerBI2 = WideWorldImporters{[Schema="dbo",Item="sp_dim_customer_powerBI2"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dbo_sp_dim_customer_powerBI2,{{"CustomerID", type text}, {"CustomerCategoryID", type text}, {"BuyingGroupID", type text}, {"DeliveryCityID", type text}, {"PostalCityID", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegaci贸n

	annotation PBI_ResultType = Table

