table fact_ordenes
	lineageTag: 70d0268b-cd89-4e36-9517-2e9b9c11af4b

	measure 'órdenes creadas' = COUNTROWS(fact_ordenes)
		formatString: #,0
		lineageTag: c6d49339-1066-4e4d-b557-d105af212f11

	measure 'órdenes facturadas' =
			CALCULATE(
			    COUNTROWS(fact_ordenes),
			    fact_ordenes[IsInvoicedOrder]= 1
			)
		formatString: #,0
		lineageTag: 7bb4d709-3e14-464c-a10f-645a261ff9ed

	measure '% Conversión pedidos' =
			DIVIDE(
			    fact_ordenes[órdenes facturadas],
			    fact_ordenes[órdenes creadas]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: e354fbe8-c4b2-4a8d-81b7-f0b6f58dd200

	measure 'órdenes pendientes' =
			CALCULATE(
			    COUNTROWS(fact_ordenes),
			    fact_ordenes[IsPendingOrder] = 1
			)
		formatString: #,0
		lineageTag: d80a739e-03b5-47bd-b50f-d1424d1ffd8b

	measure 'órdenes a tiempo' =
			
			CALCULATE(
			    COUNTROWS(fact_ordenes),
			    fact_ordenes[IsOnTimeDelivery] = 1
			)
		formatString: #,0
		lineageTag: f151404e-840b-4a81-a655-69596ec0d3ce

	measure '% Cumplimiento entrega' =
			
			DIVIDE(
			    fact_ordenes[órdenes a tiempo],
			    fact_ordenes[órdenes facturadas]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 510ee186-80e8-48db-a0b6-ec004624ac3e

	measure '% Órdenes pendientes' =
			DIVIDE(
			    fact_ordenes[órdenes pendientes],
			    fact_ordenes[órdenes creadas]
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 16793984-9eb3-42f6-b1c5-5020a408e7ec

	measure 'Tickets promedio' = DIVIDE(fact_ventas[ventas totales] , fact_ordenes[total ordenes])
		lineageTag: f2332108-5a91-4e79-bfc0-83b3e505bff5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'total ordenes' = DISTINCTCOUNT( fact_ordenes[OrderID])
		formatString: 0
		lineageTag: 83805dd2-1ba3-454e-b901-5159527ac213

	measure 'órdenes año anterior' =
			CALCULATE(
			    [total ordenes],
			    SAMEPERIODLASTYEAR(dim_fecha[FullDate]
			    ))
		lineageTag: 87d2daac-d2f6-48ac-87fa-ed4316accf52

	measure 'variación de ordenes' = [total ordenes] - fact_ordenes[órdenes año anterior]
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 8dd2ffe3-f179-44ca-9356-9eb4c7bd3959

	measure 'ticket año anterior' =
			CALCULATE( [Tickets promedio],
			SAMEPERIODLASTYEAR(dim_fecha[FullDate]
			))
		lineageTag: 423548ea-2cf0-4eaf-88cd-3a6849be5d71

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'variación de tickets' = [Tickets promedio] -[ticket año anterior]
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 7119a917-8fd9-43ee-b1bc-8663d757e4d9

	column OrderID
		dataType: string
		lineageTag: 83ba4eb2-2df0-4d34-9304-6ed1cf569b88
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		lineageTag: fe9bb3bf-dc59-4117-95e9-b3c299c90669
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: afbde66e-020d-4378-8076-c14913a2071a
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ExpectedDeliveryDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8c579a6a-bc7f-4b1a-9588-3b0f98ae8d41
		summarizeBy: none
		sourceColumn: ExpectedDeliveryDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PickingCompletedWhen
		dataType: dateTime
		formatString: General Date
		lineageTag: 9523eb76-378b-4668-97a9-4c911a336223
		summarizeBy: none
		sourceColumn: PickingCompletedWhen

		annotation SummarizationSetBy = Automatic

	column IsInvoicedOrder
		dataType: int64
		formatString: 0
		lineageTag: c421963e-cb5d-429e-9fc0-753bc69ae966
		summarizeBy: none
		sourceColumn: IsInvoicedOrder

		annotation SummarizationSetBy = Automatic

	column IsPendingOrder
		dataType: int64
		formatString: 0
		lineageTag: c682d48b-bcdb-4c6a-98a0-35151e19a620
		summarizeBy: none
		sourceColumn: IsPendingOrder

		annotation SummarizationSetBy = Automatic

	column IsOnTimeDelivery
		dataType: int64
		formatString: 0
		lineageTag: 44316639-06fa-4504-8488-1c24fd47476d
		summarizeBy: none
		sourceColumn: IsOnTimeDelivery

		annotation SummarizationSetBy = Automatic

	partition fact_ordenes = m
		mode: import
		source =
				let
				    Origen = Sql.Database(".\SQLEXPRESS", "WideWorldImporters"),
				    dbo_sp_fact_orders_powerBI2 = Origen{[Schema="dbo",Item="sp_fact_orders_powerBI2"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dbo_sp_fact_orders_powerBI2,{{"OrderID", type text}, {"CustomerID", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

